/**
 * Created by houruhou on 2021/12/17/11:40 AM
 * Desc:
 */
object Libs {
    const val ACTIVITY_KTX = "androidx.activity:activity-ktx"
    const val APPCOMPAT = "androidx.appcompat:appcompat"
    const val CARDVIEW = "androidx.cardview:cardview"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout"
    const val CORE_KTX = "androidx.core:core-ktx"
    const val EXT_JUNIT = "androidx.test.ext:junit"
    const val ESPRESSO_CORE = "androidx.test.espresso:espresso-core"
    const val FLEXBOX = "com.google.android:flexbox"
    const val FRAGMENT_KTX = "androidx.fragment:fragment-ktx"
    const val GLIDE = "com.github.bumptech.glide:glide"
    const val GLIDE_COMPILER = "com.github.bumptech.glide:compiler"
    const val GSON = "com.google.code.gson:gson"
    const val HAMCREST = "org.hamcrest:hamcrest-library"
    const val HILT_ANDROID = "com.google.dagger:hilt-android"
    const val HILT_COMPILER = "com.google.dagger:hilt-android-compiler"
    const val HILT_TESTING = "com.google.dagger:hilt-android-testing"
    const val INK_PAGE_INDICATOR = "com.pacioianu.david:ink-page-indicator"
    const val JUNIT = "junit:junit"
    const val KOTLIN_STDLIB = "org.jetbrains.kotlin:kotlin-stdlib"
    const val LIFECYCLE_COMPILER = "androidx.lifecycle:lifecycle-compiler"
    const val LIFECYCLE_LIVE_DATA_KTX = "androidx.lifecycle:lifecycle-livedata-ktx"
    const val LIFECYCLE_RUNTIME_KTX = "androidx.lifecycle:lifecycle-runtime-ktx"
    const val LIFECYCLE_VIEW_MODEL_KTX = "androidx.lifecycle:lifecycle-viewmodel-ktx"
    const val LOTTIE = "com.airbnb.android:lottie"
    const val MATERIAL = "com.google.android.material:material"
    const val OKHTTP = "com.squareup.okhttp3:okhttp"
    const val OKHTTP_LOGGING_INTERCEPTOR = "com.squareup.okhttp3:logging-interceptor"
    const val OKIO = "com.squareup.okio:okio"
    const val ROOM_COMPILER = "androidx.room:room-compiler"
    const val ROOM_KTX = "androidx.room:room-ktx"
    const val ROOM_RUNTIME = "androidx.room:room-runtime"
    const val SLIDING_PANE_LAYOUT = "androidx.slidingpanelayout:slidingpanelayout"
    const val VIEWPAGER2 = "androidx.viewpager2:viewpager2"
}